// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU8_44-dryoRnwSutnAD4LCZB7uH4fWCc',
    appId: '1:665469564518:web:3afa4876a45878385c1fa7',
    messagingSenderId: '665469564518',
    projectId: 'tashs-project',
    authDomain: 'tashs-project.firebaseapp.com',
    storageBucket: 'tashs-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdzNfCjrSDMn5dCLpoYcPe9tmZghTKJcc',
    appId: '1:665469564518:android:dffa4bc54be65fba5c1fa7',
    messagingSenderId: '665469564518',
    projectId: 'tashs-project',
    storageBucket: 'tashs-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRsZACB0p6CeyFpK0lg9XCMpQVgabpmic',
    appId: '1:665469564518:ios:e7bc7733109db1705c1fa7',
    messagingSenderId: '665469564518',
    projectId: 'tashs-project',
    storageBucket: 'tashs-project.firebasestorage.app',
    iosBundleId: 'com.example.tasksProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRsZACB0p6CeyFpK0lg9XCMpQVgabpmic',
    appId: '1:665469564518:ios:e7bc7733109db1705c1fa7',
    messagingSenderId: '665469564518',
    projectId: 'tashs-project',
    storageBucket: 'tashs-project.firebasestorage.app',
    iosBundleId: 'com.example.tasksProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU8_44-dryoRnwSutnAD4LCZB7uH4fWCc',
    appId: '1:665469564518:web:e5e144a64feee4cb5c1fa7',
    messagingSenderId: '665469564518',
    projectId: 'tashs-project',
    authDomain: 'tashs-project.firebaseapp.com',
    storageBucket: 'tashs-project.firebasestorage.app',
  );
}
